packages:
  - 'plugins/*'

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  workerd: false

patchedDependencies:
  '@emdash-cms/cloudflare@0.27.0': patches/@emdash-cms__cloudflare@0.27.0.patch
  '@emdash-cms/plugin-atproto@0.2.1': patches/@emdash-cms__plugin-atproto@0.2.1.patch
