// Generated by EmDash CLI
// Do not edit manually - run `emdash types` to regenerate

import type {
	ContentBylineCredit,
	PortableTextBlock,
	TaxonomyTerm,
} from 'emdash';

export interface Post {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	body?: PortableTextBlock[];
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
	terms?: Record<string, TaxonomyTerm[]>;
}
