backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/index.md'
        label: 'Home Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Image, name: image, widget: image }
          - { label: 'Body', name: 'body', widget: 'markdown' }
